token: "FMnN93zRX0Ek6GR1"    # Lichess OAuth2 Token.
url: "https://lichess.org/"  # Lichess base URL.

engine:                      # Engine settings.
  dir: "./engines/"          # Directory containing engines, relative to this project.
  #name: "stockfish.exe"
  #name: "sf_c.exe"
  name: "sf_haswell.exe"        # Binary name of the engine to use.
  #name: "stockfish_tuned.exe"
  protocol: "uci"            # "uci" or "xboard"
  ponder: true               # Think on opponent's time.
  polyglot:
    enabled: true           # Activate polyglot book.
    book:
      standard:              # List of book file paths for variant standard.
        #- engines/Cerebellum3Merge.bin
        #- engines/experience_book.bin
        - engines/book1.bin
        - engines/Perfect2017-SF12.bin
        - engines/Perfect2017-LC0.bin
        - engines/Perfect2017.bin
        #- engines/book2.bin
#     atomic:                # List of book file paths for variant atomic.
#       - engines/atomicbook1.bin
#       - engines/atomicbook2.bin
#     etc.
#     Use the same pattern for 'giveaway' (antichess), 'crazyhouse', 'horde', 'kingofthehill', 'racingkings' and '3check' as well.
    min_weight: 0            # Does not select moves with weight below min_weight (min 0, max: 65535).
    selection: "best_move" # Move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in the 2nd and 3rd case).
    max_depth: 100             # Half move max depth.
  #engine_options:            # Any custom command line params to pass to the engine.
    #cpuct: 3.7
  uci_options:               # Arbitrary UCI options passed to the engine.
    Move Overhead: 0       # Increase if your bot flags games too often.
    Threads: 2               # Max CPU threads the engine can use.
    Hash: 4096                # Max memory (in megabytes) the engine can allocate.
    #USE nnue: true
    #EvalFile: nn-62ef826d1a6d.nnue
    Contempt: 0
    #SyzygyPath: engines/syzygy
#    go_commands:             # Additional options to pass to the UCI go command.
#     nodes: 1               # Search so many nodes only.
#      depth: 5               # Search depth ply only.
#     movetime: 1000         # Integer. Search exactly movetime milliseconds.
# xboard_options:            # Arbitrary XBoard options passed to the engine.
#   cores: "4"
#   memory: "4096"
#   egtpath:                 # Directory containing egtb (endgame tablabases), relative to this project. For 'xboard' engines.
#     gaviota: "Gaviota path"
#     nalimov: "Nalimov Path"
#     scorpio: "Scorpio Path"
#     syzygy: "Syzygy Path"
#   go_commands:             # Additional options to pass to the XBoard go command.
#     depth: 5               # Search depth ply only.
#     Do note that the go commands 'movetime' and 'nodes' are invalid and may cause bad time management for XBoard engines.
  silence_stderr: false      # Some engines (yes you, Leela) are very noisy.

abort_time: 20               # Time to abort a game in seconds when there is no activity.
fake_think_time: false       # Artificially slow down the bot to pretend like it's thinking.
rate_limiting_delay: 0       # Time (in ms) to delay after sending a move to prevent "Too Many Requests" errors.
move_overhead: 0          # Increase if your bot flags games too often.

challenge:                   # Incoming challenges.
  concurrency: 1             # Number of games to play simultaneously.
  sort_by: "best"            # Possible values: "best" and "first".
  accept_bot: true          # Accepts challenges coming from other bots.
  only_bot: false            # Accept challenges by bots only.
  max_increment: 180         # Maximum amount of increment to accept a challenge. The max is 180. Set to 0 for no increment.
  min_increment: 0           # Minimum amount of increment to accept a challenge.
  max_base: 315360000        # Maximum amount of base time to accept a challenge. The max is 315360000 (10 years).
  min_base: 0                # Minimum amount of base time to accept a challenge.
  variants:                  # Chess variants to accept (https://lichess.org/variant).
    - standard
#   - fromPosition
#   - antichess
#   - atomic
    - chess960
#   - crazyhouse
#   - horde
#   - kingOfTheHill
#   - racingKings
#   - threeCheck
  time_controls:             # Time controls to accept.
    - bullet
    - blitz
    - rapid
#   - classical
#   - correspondence
  modes:                     # Game modes to accept.
    - casual                 # Unrated games.
 #   - rated                  # Rated games - must comment if the engine doesn't try to win.