token: "xxxxxxxxxxxxxxxx"    # lichess OAuth2 Token hahayoulost06
url: "https://lichess.org/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "stockfish.exe"     #haswell???
  protocol: "uci"            # "uci" or "xboard"
  uci_ponder: true           # think on opponent time; only works if "protocol" is "uci"
  polyglot:
    enabled: true           # activate polyglot book
    book:
      standard: # list of book file paths for variant standard
        - engines/book1.bin
      min_weight: 0            # does not select moves with weight below min_weight (min 0, max: 65535)
    selection: "best_move" # move selection is one of "weighted_random", "uniform_random" or "best_move" (but not below the min_weight in 2. and 3. case)
    max_depth:  999             # half move max depth
  uci_options:               # arbitrary UCI options passed to the engine
    Move Overhead: 0       # increase if your bot flags games too often
    Threads: 2               # max CPU threads the engine can use
    Hash: 256               # max memory (in megabytes) the engine can allocate
    Contempt: 0
  silence_stderr: true      # some engines (yes you, leela) are very noisy

abort_time: 20               # time to abort a game in seconds when there is no activity
fake_think_time: false       # artificially slow down the bot to pretend like it's thinking
move_overhead: 0          # increase if your bot flags games too often

challenge:                   # incoming challenges
  concurrency: 1             # number of games to play simultaneously
  sort_by: "best"            # possible values: "best", "first"
  accept_bot: true          # accepts challenges coming from other bots
  only_bot: false            # accept challenges by bots only
  max_increment: 180         # maximum amount of increment to accept a challenge. the max is 180. set to 0 for no increment
  min_increment: 0           # minimum amount of increment to accept a challenge
  max_base: 315360000        # maximum amount of base time to accept a challenge. the max is 315360000 (10 years)
  min_base: 0                # minimum amount of base time to accept a challenge
  variants:                  # chess variants to accept (http://lichess.org/variant)
   - standard
   # - fromPosition
   # - antichess
   # - atomic
   - chess960
   # - crazyhouse
   # - horde
   # - kingOfTheHill
   # - racingKings
   # - threeCheck
  time_controls:             # time controls to accept
    - bullet
    - blitz
    - rapid
#   - classical
#   - correspondence
  modes:                     # game modes to accept
    - casual                 # unrated games
    - rated                  # rated games - must comment if the engine doesn't try to win
